using System;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel;
using Progress.Sitefinity.AspNetCore.ViewComponents;

namespace ViewComponents.SeparatedViewsWidget
{
    /// <summary>
    /// Test widget with different kind of restrictions for its properties. For more information on creating widgets
    /// visit <see href="https://www.progress.com/documentation/sitefinity-cms/asp.net-core-widget-components">this page.</see>
    /// </summary>
    [SitefinityWidget(Title = "Separated Views Widget", EmptyIcon ="hand-peace-o", EmptyIconText ="Lino was here", SeparateWidgetPerTemplate = true)]
    public class SeparatedViewsWidgetViewComponent : ViewComponent
    {
        /// <summary>
        /// Invokes the view.
        /// </summary>
        /// <param name="context"></param>
        /// <returns></returns>
        public IViewComponentResult Invoke(IViewComponentContext<SeparatedViewsWidgetEntity> context)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }

            return this.View(context.Entity.sfViewName);
        }
    }

    /// <summary>
    /// The test model for the load tests widget. For a list of supported properties
    /// visit <see href="https://www.progress.com/documentation/sitefinity-cms/autogenerated-field-types">this page.</see>
    /// </summary>
    public class SeparatedViewsWidgetEntity
    {
        /// <summary>
        /// Gets or sets a value indicating whether a boolean property is true or false.
        /// </summary>
        [Browsable(false)]
        public string sfViewName { get; set; }
    }
}
